name: CI Build

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore Dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --version-suffix "ci.${{ github.run_id }}"
    - name: Test
      run: dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: "./Source/*/bin/**"

  Publish:
    runs-on: ubuntu-latest
    environment: publish
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: binaries
    - name: Push NuGet Package
      run: dotnet nuget push "**/*.nupkg" -k ${{ secrets.NuGetAPIKey }}