name: Release Build

on:
  workflow_dispatch: {}

jobs:
  build:
    uses: ./.github/workflows/template-build.yml
  publish:
    uses: ./.github/workflows/template-publish.yml
    needs: [ build ]
    secrets: inherit
